# Generated by Django 4.0.4 on 2022-05-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_cartitem_price_ht_alter_order_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='newprice',
            field=models.DecimalField(decimal_places=2, default=6666, max_digits=10),
            preserve_default=False,
        ),
    ]
