# Generated by Django 4.0.4 on 2022-05-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_computer_newprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='promocode',
        ),
    ]
