# Generated by Django 4.0.4 on 2022-06-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_computer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_status',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50)),
            ],
        ),
    ]
